# Importing Library

In [1]:
import numpy as np

# Array Atrributes

In [2]:
a = np.array([1, 2, 3]) # 1-D / Vector

In [3]:
a

array([1, 2, 3])

In [4]:
# check the type of an array
type(a)

numpy.ndarray

In [5]:
# shape of the array
a.shape

(3,)

In [6]:
# dimension of the array
a.ndim

1

In [7]:
b = np.array([[1, 2, 3],     # 2-D array / Matrix
              [4, 5, 6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 3)

In [11]:
b.ndim

2

In [12]:
# 3-D arrays

c = np.array([[[1.0, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])

d = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
             
             [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [13]:
c

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [14]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [16]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('int32'), dtype('float64'), dtype('int32'))

In [17]:
a.size, b.size, c.size, d.size # determine how many elements are there in an array

(3, 6, 9, 18)

In [18]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes # determine how many bytes consumed by an array

(12, 24, 72, 72)

# Array Creation

In [19]:
array1 = np.array([1, 2, 3], dtype = 'int')

In [20]:
array1

array([1, 2, 3])

In [21]:
zeros = np.zeros((3, 3), dtype = 'int')  # Return a new array of given shape and type, filled with zeros

In [22]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
ones = np.ones((3, 3), dtype = 'int') # Return a new array of given shape and type, filled with ones

In [24]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
full = np.full((2,3), 5) # Return a new array of given shape and type, filled with given value

In [26]:
full

array([[5, 5, 5],
       [5, 5, 5]])

In [27]:
identity = np.identity(3, dtype = 'int') # Return the identity array.

In [28]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
eye = np.eye(3,3)

In [30]:
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arange = np.arange(1, 10, 2) # Return evenly spaced values within a given interval.

In [32]:
arange

array([1, 3, 5, 7, 9])

In [33]:
linspace = np.linspace(1, 100, 50, dtype = 'int') # Return evenly spaced numbers over a specified interval.

In [34]:
linspace

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [35]:
linspace.size

50

In [36]:
empty = np.empty((1,5)) # Return a new array of given shape and type, without initializing entries.

In [37]:
empty

array([[2.12199579e-314, 3.33773471e-307, 5.69163624e-321,
        2.12199583e-313, 1.05700260e-307]])

In [38]:
for i in range(5):
    empty[:,i] = i
empty

array([[0., 1., 2., 3., 4.]])

# Array indexing and Slicing

### indexing

In [39]:
arr1 = np.array([1, 2, 3, 4, 5])

In [40]:
print(arr1)

[1 2 3 4 5]


In [41]:
arr1[0]

1

In [42]:
arr1[3]

4

In [43]:
arr1[-1]

5

In [44]:
arr2 = np.random.randint(1, 10, size = (3,3))

In [45]:
print(arr2)

[[8 6 3]
 [2 6 8]
 [4 9 7]]


In [46]:
arr2[0][0]

8

In [47]:
arr2[1][1]

6

In [48]:
arr2[1, 1]

6

In [49]:
arr3 = np.random.randint(1, 10, size = (2, 3, 3))

In [50]:
print(arr3)

[[[4 3 3]
  [3 1 9]
  [9 7 8]]

 [[4 1 1]
  [6 2 2]
  [9 2 5]]]


In [51]:
arr3[0][1][1]

1

In [52]:
arr3[0, 1, 1]

1

In [53]:
arr3[1, 2, 1]

2

### Slicing 

In [54]:
print(arr1)

[1 2 3 4 5]


In [55]:
print(arr1[: 3])

[1 2 3]


In [56]:
print(arr1[2:])

[3 4 5]


In [57]:
arr2

array([[8, 6, 3],
       [2, 6, 8],
       [4, 9, 7]])

In [58]:
arr2[0: 2, 0:2]

array([[8, 6],
       [2, 6]])

In [59]:
arr2[1:, 1:]

array([[6, 8],
       [9, 7]])

# Manipilating array shapes


  1. reshape()
  2. resize()
  3. flatten()
  4. revel()
  5. defining array shape

#### reshape()

In [60]:
a = np.array([[1, 2, 3],
            [4, 5, 6]])

In [61]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
a.shape

(2, 3)

In [63]:
a_reshaped = np.reshape(a, (3, 2)) # Gives a new shape to an array without changing its data.

In [64]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
a_reshaped.shape

(3, 2)

In [66]:
a_reshaped2 = np.reshape(a, (3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

#### resize()

In [67]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a_resized = np.resize(a, (4, 3)) # Return a new array with the specified shape.

In [69]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
a_resized2 = np.resize(a, (3, 2))

In [71]:
a_resized2

array([[1, 2],
       [3, 4],
       [5, 6]])